version: '3.8'

services:
  # Сервис для PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations/1_initial_schema.up.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Сервис для Go-сервера
  go-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PG_URL=postgres://user:password@postgres:5432/my-database
      - CONN=http://python_server:5000
    ports:
      - "8090:8090"
    networks:
      - app-network
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "--", "./main"]

  # Сервис для Python-сервера
  python_server:
    build:
      context: ./python
    ports:
      - "5000:5000"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    external: true
